version: "3.8"

networks:
  kafka_network:

x-check-ports: &check-ports ./bin/check-ports:/bin/check-ports
x-service-template: &template
  restart: on-failure
  networks:
    - kafka_network
  healthcheck: &hc
    interval: 5s
    timeout: 3s
    start_period: 10s
    retries: 20
  volumes:
    - *check-ports
    - ./bin/bashrc:/home/appuser/.bashrc

services:
  prometheus:
    <<: *template
    image: prom/prometheus
    hostname: &name prometheus
    container_name: *name
    ports:
      - "9090:9090"
    healthcheck:
      <<: *hc
      test: sh /bin/check-ports 9090
    volumes:
      - *check-ports
      - ./prometheus:/etc/prometheus

  kafka:
    <<: *template
    image: confluentinc/cp-kafka:7.5.3
    hostname: &name kafka
    container_name: *name
    ports:
      - "1234:1234"
      - "9010:9010"
    healthcheck:
      <<: *hc
      test: /bin/check-ports 9092 19092 1234 9010
    volumes:
      - *check-ports
      - ./prometheus:/etc/prometheus
      - ./jmx-exporter:/usr/share/jmx-exporter
      - ./jfr:/tmp/jfr
    environment:
      CLUSTER_ID: JS-9P8KdQGG_lCVXikxM5w
      KAFKA_NODE_ID: 1

      KAFKA_PROCESS_ROLES: >
        controller,
        broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:19092

      KAFKA_LISTENERS: &listeners BROKER://kafka:9092, CONTROLLER://kafka:19092
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >
        BROKER:PLAINTEXT,
        CONTROLLER:PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      EXTRA_ARGS: >
        -javaagent:/usr/share/jmx-exporter/jmx_prometheus_javaagent.jar=1234:/usr/share/jmx-exporter/kafka_broker.yml
        -XX:StartFlightRecording=filename=/tmp/jfr/file.jfr
        -Dcom.sun.management.jmxremote
        -Dcom.sun.management.jmxremote.port=9010
        -Dcom.sun.management.jmxremote.rmi.port=9010
        -Dcom.sun.management.jmxremote.local.only=true
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false
        -Djava.rmi.server.hostname=127.0.0.1
