global:
  # How frequently to scrape targets by default.
  # Default 15s
  scrape_interval: 10s
  # How frequently to evaluate rules.
  # Default 15s
  evaluation_interval: 10s
  # How long until a scrape request times out.
  # Default to 10s.
  scrape_timeout: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "kafka"
    static_configs:
      - targets:
          - "kafka:1234"
        labels:
          env: "dev"
    relabel_configs:
      - source_labels: [__address__]
        target_label: hostname
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'
